#!/bin/sh

set -e
set -u

__DIR__="$(cd "$(dirname "$0")" && pwd)"

source $__DIR__/functions.sh

command=false
if [ "$#" -gt 0 ]; then
  command="$1"
  shift
fi

if [ ! -f "$__DIR__/_$command.sh" ]; then
  exit 1
fi

"$__DIR__/_$command.sh" "$@"
