FROM ubuntu:26.04

LABEL MAINTAINER="brudermusscode <justin@heia.kim>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -q && \
    apt install -y \
    apt-transport-https \
    lsb-release \
    software-properties-common \
    gnupg2 \
    curl \
    ca-certificates \
    ubuntu-keyring \
    libzip-dev \
    libicu-dev \
    libcurl4-openssl-dev \
    git \
    zip \
    unzip \
    nodejs

# PHP.
# RUN add-apt-repository ppa:ondrej/php

# nginx. Why ondrej, why we need this instead of your ppa :(
RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://nginx.org/keys/nginx_signing.key \
    | gpg --dearmor -o /etc/apt/keyrings/nginx.gpg

RUN echo "deb [signed-by=/etc/apt/keyrings/nginx.gpg] \
    http://nginx.org/packages/ubuntu $(lsb_release -cs) nginx" \
    > /etc/apt/sources.list.d/nginx.list

# Install everything we need for the app.
RUN apt update -q && \
    apt install -y \
    nginx \
    php8.5 \
    php8.5-cli \
    php8.5-fpm \
    php8.5-common \
    php8.5-bz2 \
    php8.5-curl \
    php8.5-mbstring \
    php8.5-intl \
    php8.5-mysql \
    php8.5-xml \
    php8.5-gd \
    php8.5-zip

RUN rm -f /var/log/nginx/access.log /var/log/nginx/error.log && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

WORKDIR /data

COPY . .

# Install composer & dependencies without dev
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && chmod 755 /usr/local/bin/composer \
    && composer install --no-dev --no-scripts

RUN composer dump-autoload

# Create dependency directories for uploaded content
RUN mkdir -p \
    public/data/user/1/tracks \
    public/data/user/1/art \
    public/data/user/1/portraits \
    public/data/user/1/videos

RUN chown www-data -R public storage

EXPOSE 80

ENTRYPOINT ["/data/docker/deploy/entrypoint.sh"]