FROM ubuntu:26.04

LABEL MAINTAINER="brudermusscode <justin@heia.kim>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -q && \
    apt install -y \
    apt-transport-https \
    lsb-release \
    software-properties-common \
    gnupg2 \
    curl \
    ca-certificates \
    ubuntu-keyring \
    libzip-dev \
    libicu-dev \
    libcurl4-openssl-dev \
    git \
    zip \
    unzip \
    nodejs

# nginx. Why ondrej, why we need this instead of your ppa :(
RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://nginx.org/keys/nginx_signing.key \
    | gpg --dearmor -o /etc/apt/keyrings/nginx.gpg

RUN echo "deb [signed-by=/etc/apt/keyrings/nginx.gpg] \
    http://nginx.org/packages/ubuntu $(lsb_release -cs) nginx" \
    > /etc/apt/sources.list.d/nginx.list

RUN apt install -y nginx
# php8.5 \
# php8.5-cli \
# php8.5-fpm \
# php8.5-common \
# php8.5-bz2 \
# php8.5-curl \
# php8.5-mbstring \
# php8.5-intl \
# php8.5-mysql \
# php8.5-xml \
# php8.5-gd \
# php8.5-zip

RUN rm -f /var/log/nginx/access.log /var/log/nginx/error.log && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

WORKDIR /data

# RUN curl -L "https://getcomposer.org/download/latest-2.x/composer.phar" > /usr/local/bin/composer && chmod 755 /usr/local/bin/composer
# COPY composer.json composer.lock ./
# RUN composer install --no-dev --no-scripts

# Copy all files of this app to the container.
COPY . .

# Install composer globally. This gets rid for the need of having
# the user to have php installed on their system. Thank you Simon
# :) May god bless you.
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
# ENV PATH="$PATH:/usr/local/bin"

# RUN composer dump-autoload

RUN chown www-data -R public storage

EXPOSE 80

ENTRYPOINT ["/data/docker/entrypoint.sh"]